[tool.poetry]
name = "fawaris"
version = "0.1.0"
description = "A small Stellar Anchor library"
authors = ["Yuri Escalianti <yuriescl@gmail.com>"]
license = "Apache License Version 2.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
